// Ported verbatim from app.js's AP/COUNTRY_DE arrays — a small
// (80-airport) client-bundled lookup used for: connecting-airport city
// names in the offer card's stop badge, the local-first autocomplete
// fallback while a debounced network search is pending, and the
// "popular destinations" list shown when the destination field is
// focused empty. Columns: [iata, name, city_de, country_de, city_en,
// city_ar, country_en, city_es, city_fr, city_it, city_nl].
const AP = [
  [
    "BER",
    "Berlin Brandenburg",
    "Berlin",
    "Deutschland",
    "Berlin",
    "برلين",
    "Germany",
    "Berlín",
    "Berlin",
    "Berlino",
    "Berlijn"
  ],
  [
    "MUC",
    "München Franz Josef Strauß",
    "München",
    "Deutschland",
    "Munich",
    "ميونخ",
    "Germany",
    "Múnich",
    "Munich",
    "Monaco di Baviera",
    "München"
  ],
  [
    "FRA",
    "Frankfurt am Main",
    "Frankfurt",
    "Deutschland",
    "Frankfurt",
    "فرانكفورت",
    "Germany",
    "Fráncfort",
    "Francfort",
    "Francoforte",
    "Frankfurt"
  ],
  [
    "HAM",
    "Hamburg Airport",
    "Hamburg",
    "Deutschland",
    "Hamburg",
    "هامبورغ",
    "Germany",
    "Hamburgo",
    "Hambourg",
    "Amburgo",
    "Hamburg"
  ],
  [
    "DUS",
    "Düsseldorf Airport",
    "Düsseldorf",
    "Deutschland",
    "Dusseldorf",
    "دوسلدورف",
    "Germany",
    "Düsseldorf",
    "Düsseldorf",
    "Düsseldorf",
    "Düsseldorf"
  ],
  [
    "CGN",
    "Köln/Bonn Airport",
    "Köln",
    "Deutschland",
    "Cologne",
    "كولونيا",
    "Germany",
    "Colonia",
    "Cologne",
    "Colonia",
    "Keulen"
  ],
  [
    "STR",
    "Stuttgart Airport",
    "Stuttgart",
    "Deutschland",
    "Stuttgart",
    "شتوتغارت",
    "Germany",
    "Stuttgart",
    "Stuttgart",
    "Stoccarda",
    "Stuttgart"
  ],
  [
    "VIE",
    "Wien-Schwechat",
    "Wien",
    "Österreich",
    "Vienna",
    "فيينا",
    "Austria",
    "Viena",
    "Vienne",
    "Vienna",
    "Wenen"
  ],
  [
    "ZRH",
    "Zürich Airport",
    "Zürich",
    "Schweiz",
    "Zurich",
    "زيورخ",
    "Switzerland",
    "Zúrich",
    "Zurich",
    "Zurigo",
    "Zürich"
  ],
  [
    "LHR",
    "London Heathrow",
    "London",
    "UK",
    "London",
    "لندن",
    "United Kingdom",
    "Londres",
    "Londres",
    "Londra",
    "Londen"
  ],
  [
    "LGW",
    "London Gatwick",
    "London",
    "UK",
    "London",
    "لندن",
    "United Kingdom",
    "Londres",
    "Londres",
    "Londra",
    "Londen"
  ],
  [
    "STN",
    "London Stansted",
    "London",
    "UK",
    "London",
    "لندن",
    "United Kingdom",
    "Londres",
    "Londres",
    "Londra",
    "Londen"
  ],
  [
    "CDG",
    "Paris Charles de Gaulle",
    "Paris",
    "Frankreich",
    "Paris",
    "باريس",
    "France",
    "París",
    "Paris",
    "Parigi",
    "Parijs"
  ],
  [
    "ORY",
    "Paris Orly",
    "Paris",
    "Frankreich",
    "Paris",
    "باريس",
    "France",
    "París",
    "Paris",
    "Parigi",
    "Parijs"
  ],
  [
    "AMS",
    "Amsterdam Schiphol",
    "Amsterdam",
    "Niederlande",
    "Amsterdam",
    "أمستردام",
    "Netherlands",
    "Ámsterdam",
    "Amsterdam",
    "Amsterdam",
    "Amsterdam"
  ],
  [
    "BRU",
    "Brüssel-Zaventem",
    "Brüssel",
    "Belgien",
    "Brussels",
    "بروكسل",
    "Belgium",
    "Bruselas",
    "Bruxelles",
    "Bruxelles",
    "Brussel"
  ],
  [
    "MAD",
    "Madrid-Barajas",
    "Madrid",
    "Spanien",
    "Madrid",
    "مدريد",
    "Spain",
    "Madrid",
    "Madrid",
    "Madrid",
    "Madrid"
  ],
  [
    "BCN",
    "Barcelona El Prat",
    "Barcelona",
    "Spanien",
    "Barcelona",
    "برشلونة",
    "Spain",
    "Barcelona",
    "Barcelone",
    "Barcellona",
    "Barcelona"
  ],
  [
    "PMI",
    "Palma de Mallorca",
    "Mallorca",
    "Spanien",
    "Mallorca",
    "مايوركا",
    "Spain",
    "Mallorca",
    "Majorque",
    "Maiorca",
    "Mallorca"
  ],
  [
    "AGP",
    "Málaga Costa del Sol",
    "Málaga",
    "Spanien",
    "Malaga",
    "ملقا",
    "Spain",
    "Málaga",
    "Malaga",
    "Málaga",
    "Málaga"
  ],
  [
    "LIS",
    "Lissabon Humberto Delgado",
    "Lissabon",
    "Portugal",
    "Lisbon",
    "لشبونة",
    "Portugal",
    "Lisboa",
    "Lisbonne",
    "Lisbona",
    "Lissabon"
  ],
  [
    "OPO",
    "Porto Francisco Sa Carneiro",
    "Porto",
    "Portugal",
    "Porto",
    "بورتو",
    "Portugal",
    "Oporto",
    "Porto",
    "Porto",
    "Porto"
  ],
  [
    "FCO",
    "Rom Fiumicino",
    "Rom",
    "Italien",
    "Rome",
    "روما",
    "Italy",
    "Roma",
    "Rome",
    "Roma",
    "Rome"
  ],
  [
    "MXP",
    "Mailand Malpensa",
    "Mailand",
    "Italien",
    "Milan",
    "ميلانو",
    "Italy",
    "Milán",
    "Milan",
    "Milano",
    "Milaan"
  ],
  [
    "VCE",
    "Venedig Marco Polo",
    "Venedig",
    "Italien",
    "Venice",
    "البندقية",
    "Italy",
    "Venecia",
    "Venise",
    "Venezia",
    "Venetië"
  ],
  [
    "ATH",
    "Athen Eleftherios Venizelos",
    "Athen",
    "Griechenland",
    "Athens",
    "أثينا",
    "Greece",
    "Atenas",
    "Athènes",
    "Atene",
    "Athene"
  ],
  [
    "IST",
    "Istanbul Airport",
    "Istanbul",
    "Türkei",
    "Istanbul",
    "إسطنبول",
    "Turkey",
    "Estambul",
    "Istanbul",
    "Istanbul",
    "Istanbul"
  ],
  [
    "AYT",
    "Antalya Airport",
    "Antalya",
    "Türkei",
    "Antalya",
    "أنطاليا",
    "Turkey",
    "Antalya",
    "Antalya",
    "Antalya",
    "Antalya"
  ],
  [
    "CPH",
    "Kopenhagen Kastrup",
    "Kopenhagen",
    "Dänemark",
    "Copenhagen",
    "كوبنهاغن",
    "Denmark",
    "Copenhague",
    "Copenhague",
    "Copenaghen",
    "Kopenhagen"
  ],
  [
    "OSL",
    "Oslo Gardermoen",
    "Oslo",
    "Norwegen",
    "Oslo",
    "أوسلو",
    "Norway",
    "Oslo",
    "Oslo",
    "Oslo",
    "Oslo"
  ],
  [
    "ARN",
    "Stockholm Arlanda",
    "Stockholm",
    "Schweden",
    "Stockholm",
    "ستوكهولم",
    "Sweden",
    "Estocolmo",
    "Stockholm",
    "Stoccolma",
    "Stockholm"
  ],
  [
    "HEL",
    "Helsinki-Vantaa",
    "Helsinki",
    "Finnland",
    "Helsinki",
    "هلسنكي",
    "Finland",
    "Helsinki",
    "Helsinki",
    "Helsinki",
    "Helsinki"
  ],
  [
    "WAW",
    "Warschau Chopin",
    "Warschau",
    "Polen",
    "Warsaw",
    "وارسو",
    "Poland",
    "Varsovia",
    "Varsovie",
    "Varsavia",
    "Warschau"
  ],
  [
    "PRG",
    "Prag Václav Havel",
    "Prag",
    "Tschechien",
    "Prague",
    "براغ",
    "Czech Republic",
    "Praga",
    "Prague",
    "Praga",
    "Praag"
  ],
  [
    "BUD",
    "Budapest Ferenc Liszt",
    "Budapest",
    "Ungarn",
    "Budapest",
    "بودابست",
    "Hungary",
    "Budapest",
    "Budapest",
    "Budapest",
    "Boedapest"
  ],
  [
    "DUB",
    "Dublin Airport",
    "Dublin",
    "Irland",
    "Dublin",
    "دبلن",
    "Ireland",
    "Dublín",
    "Dublin",
    "Dublino",
    "Dublin"
  ],
  [
    "EDI",
    "Edinburgh Airport",
    "Edinburgh",
    "UK",
    "Edinburgh",
    "إدنبرة",
    "United Kingdom",
    "Edimburgo",
    "Édimbourg",
    "Edimburgo",
    "Edinburgh"
  ],
  [
    "MAN",
    "Manchester Airport",
    "Manchester",
    "UK",
    "Manchester",
    "مانشستر",
    "United Kingdom",
    "Mánchester",
    "Manchester",
    "Manchester",
    "Manchester"
  ],
  [
    "GVA",
    "Genf Airport",
    "Genf",
    "Schweiz",
    "Geneva",
    "جنيف",
    "Switzerland",
    "Ginebra",
    "Genève",
    "Ginevra",
    "Genève"
  ],
  [
    "NCE",
    "Nizza Côte Azur",
    "Nizza",
    "Frankreich",
    "Nice",
    "نيس",
    "France",
    "Niza",
    "Nice",
    "Nizza",
    "Nice"
  ],
  [
    "JFK",
    "New York Kennedy",
    "New York",
    "USA",
    "New York",
    "نيويورك",
    "USA",
    "Nueva York",
    "New York",
    "New York",
    "New York"
  ],
  [
    "LAX",
    "Los Angeles Intl",
    "Los Angeles",
    "USA",
    "Los Angeles",
    "لوس أنجلوس",
    "USA",
    "Los Ángeles",
    "Los Angeles",
    "Los Angeles",
    "Los Angeles"
  ],
  [
    "MIA",
    "Miami Intl",
    "Miami",
    "USA",
    "Miami",
    "ميامي",
    "USA",
    "Miami",
    "Miami",
    "Miami",
    "Miami"
  ],
  [
    "ORD",
    "Chicago O Hare",
    "Chicago",
    "USA",
    "Chicago",
    "شيكاغو",
    "USA",
    "Chicago",
    "Chicago",
    "Chicago",
    "Chicago"
  ],
  [
    "BOS",
    "Boston Logan",
    "Boston",
    "USA",
    "Boston",
    "بوسطن",
    "USA",
    "Boston",
    "Boston",
    "Boston",
    "Boston"
  ],
  [
    "YYZ",
    "Toronto Pearson",
    "Toronto",
    "Kanada",
    "Toronto",
    "تورنتو",
    "Canada",
    "Toronto",
    "Toronto",
    "Toronto",
    "Toronto"
  ],
  [
    "DXB",
    "Dubai Intl",
    "Dubai",
    "VAE",
    "Dubai",
    "دبي",
    "UAE",
    "Dubái",
    "Dubaï",
    "Dubai",
    "Dubai"
  ],
  [
    "AUH",
    "Abu Dhabi Intl",
    "Abu Dhabi",
    "VAE",
    "Abu Dhabi",
    "أبوظبي",
    "UAE",
    "Abu Dabi",
    "Abou Dabi",
    "Abu Dhabi",
    "Abu Dhabi"
  ],
  [
    "DOH",
    "Doha Hamad",
    "Doha",
    "Katar",
    "Doha",
    "الدوحة",
    "Qatar",
    "Doha",
    "Doha",
    "Doha",
    "Doha"
  ],
  [
    "CAI",
    "Kairo Intl",
    "Kairo",
    "Ägypten",
    "Cairo",
    "القاهرة",
    "Egypt",
    "El Cairo",
    "Le Caire",
    "Il Cairo",
    "Caïro"
  ],
  [
    "HRG",
    "Hurghada Intl",
    "Hurghada",
    "Ägypten",
    "Hurghada",
    "الغردقة",
    "Egypt",
    "Hurgada",
    "Hurghada",
    "Hurghada",
    "Hurghada"
  ],
  [
    "SSH",
    "Sharm El Sheikh",
    "Sharm El Sheikh",
    "Ägypten",
    "Sharm El Sheikh",
    "شرم الشيخ",
    "Egypt",
    "Sharm el Sheij",
    "Charm el-Cheikh",
    "Sharm el-Sheikh",
    "Sharm el-Sheikh"
  ],
  [
    "TLV",
    "Tel Aviv Ben Gurion",
    "Tel Aviv",
    "Israel",
    "Tel Aviv",
    "تل أبيب",
    "Israel",
    "Tel Aviv",
    "Tel-Aviv",
    "Tel Aviv",
    "Tel Aviv"
  ],
  [
    "CMN",
    "Casablanca Mohammed V",
    "Casablanca",
    "Marokko",
    "Casablanca",
    "الدار البيضاء",
    "Morocco",
    "Casablanca",
    "Casablanca",
    "Casablanca",
    "Casablanca"
  ],
  [
    "RAK",
    "Marrakesch Menara",
    "Marrakesch",
    "Marokko",
    "Marrakech",
    "مراكش",
    "Morocco",
    "Marrakech",
    "Marrakech",
    "Marrakech",
    "Marrakech"
  ],
  [
    "BKK",
    "Bangkok Suvarnabhumi",
    "Bangkok",
    "Thailand",
    "Bangkok",
    "بانكوك",
    "Thailand",
    "Bangkok",
    "Bangkok",
    "Bangkok",
    "Bangkok"
  ],
  [
    "HKT",
    "Phuket Intl",
    "Phuket",
    "Thailand",
    "Phuket",
    "فوكيت",
    "Thailand",
    "Phuket",
    "Phuket",
    "Phuket",
    "Phuket"
  ],
  [
    "SIN",
    "Singapur Changi",
    "Singapur",
    "Singapur",
    "Singapore",
    "سنغافورة",
    "Singapore",
    "Singapur",
    "Singapour",
    "Singapore",
    "Singapore"
  ],
  [
    "KUL",
    "Kuala Lumpur Intl",
    "Kuala Lumpur",
    "Malaysia",
    "Kuala Lumpur",
    "كوالالمبور",
    "Malaysia",
    "Kuala Lumpur",
    "Kuala Lumpur",
    "Kuala Lumpur",
    "Kuala Lumpur"
  ],
  [
    "HKG",
    "Hongkong Intl",
    "Hongkong",
    "China",
    "Hong Kong",
    "هونغ كونغ",
    "China",
    "Hong Kong",
    "Hong Kong",
    "Hong Kong",
    "Hongkong"
  ],
  [
    "NRT",
    "Tokio Narita",
    "Tokio",
    "Japan",
    "Tokyo",
    "طوكيو",
    "Japan",
    "Tokio",
    "Tokyo",
    "Tokyo",
    "Tokio"
  ],
  [
    "ICN",
    "Seoul Incheon",
    "Seoul",
    "Südkorea",
    "Seoul",
    "سيول",
    "South Korea",
    "Seúl",
    "Séoul",
    "Seul",
    "Seoel"
  ],
  [
    "DEL",
    "Delhi Indira Gandhi",
    "Delhi",
    "Indien",
    "Delhi",
    "دلهي",
    "India",
    "Delhi",
    "Delhi",
    "Delhi",
    "Delhi"
  ],
  [
    "BOM",
    "Mumbai Chhatrapati",
    "Mumbai",
    "Indien",
    "Mumbai",
    "مومباي",
    "India",
    "Bombay",
    "Bombay",
    "Mumbai",
    "Mumbai"
  ],
  [
    "MLE",
    "Malé Velana",
    "Malé",
    "Malediven",
    "Male",
    "ماليه",
    "Maldives",
    "Malé",
    "Malé",
    "Malé",
    "Malé"
  ],
  [
    "SYD",
    "Sydney Kingsford Smith",
    "Sydney",
    "Australien",
    "Sydney",
    "سيدني",
    "Australia",
    "Sídney",
    "Sydney",
    "Sydney",
    "Sydney"
  ],
  [
    "GRU",
    "São Paulo Guarulhos",
    "São Paulo",
    "Brasilien",
    "Sao Paulo",
    "ساو باولو",
    "Brazil",
    "São Paulo",
    "São Paulo",
    "San Paolo",
    "São Paulo"
  ],
  [
    "CUN",
    "Cancún Intl",
    "Cancún",
    "Mexiko",
    "Cancun",
    "كانكون",
    "Mexico",
    "Cancún",
    "Cancún",
    "Cancún",
    "Cancún"
  ],
  [
    "JNB",
    "Johannesburg OR Tambo",
    "Johannesburg",
    "Südafrika",
    "Johannesburg",
    "جوهانسبرغ",
    "South Africa",
    "Johannesburgo",
    "Johannesburg",
    "Johannesburg",
    "Johannesburg"
  ],
  [
    "CPT",
    "Kapstadt Intl",
    "Kapstadt",
    "Südafrika",
    "Cape Town",
    "كيب تاون",
    "South Africa",
    "Ciudad del Cabo",
    "Le Cap",
    "Città del Capo",
    "Kaapstad"
  ],
  [
    "RUH",
    "Riad King Khalid",
    "Riad",
    "Saudi-Arabien",
    "Riyadh",
    "الرياض",
    "Saudi Arabia",
    "Riad",
    "Riyad",
    "Riyadh",
    "Riyad"
  ],
  [
    "JED",
    "Jeddah King Abdulaziz",
    "Jeddah",
    "Saudi-Arabien",
    "Jeddah",
    "جدة",
    "Saudi Arabia",
    "Yeda",
    "Djeddah",
    "Gedda",
    "Jedda"
  ],
  [
    "AMM",
    "Amman Queen Alia",
    "Amman",
    "Jordanien",
    "Amman",
    "عمّان",
    "Jordan",
    "Ammán",
    "Amman",
    "Amman",
    "Amman"
  ],
  [
    "BEY",
    "Beirut Rafic Hariri",
    "Beirut",
    "Libanon",
    "Beirut",
    "بيروت",
    "Lebanon",
    "Beirut",
    "Beyrouth",
    "Beirut",
    "Beiroet"
  ],
  [
    "KWI",
    "Kuwait Intl",
    "Kuwait",
    "Kuwait",
    "Kuwait City",
    "الكويت",
    "Kuwait",
    "Ciudad de Kuwait",
    "Koweït",
    "Kuwait City",
    "Koeweit-Stad"
  ],
  [
    "BAH",
    "Bahrain Intl",
    "Manama",
    "Bahrain",
    "Manama",
    "المنامة",
    "Bahrain",
    "Manama",
    "Manama",
    "Manama",
    "Manama"
  ],
  [
    "MCT",
    "Maskat Intl",
    "Maskat",
    "Oman",
    "Muscat",
    "مسقط",
    "Oman",
    "Mascate",
    "Mascate",
    "Mascate",
    "Muscat"
  ],
  [
    "ALG",
    "Algier Houari Boumediene",
    "Algier",
    "Algerien",
    "Algiers",
    "الجزائر",
    "Algeria",
    "Argel",
    "Alger",
    "Algeri",
    "Algiers"
  ],
  [
    "TUN",
    "Tunis-Carthage",
    "Tunis",
    "Tunesien",
    "Tunis",
    "تونس",
    "Tunisia",
    "Túnez",
    "Tunis",
    "Tunisi",
    "Tunis"
  ],
  [
    "MRS",
    "Marseille Provence",
    "Marseille",
    "Frankreich",
    "Marseille",
    "مارسيليا",
    "France",
    "Marsella",
    "Marseille",
    "Marsiglia",
    "Marseille"
  ]
];

const COUNTRY_DE = {
  "AD": "Andorra",
  "AE": "Vereinigte Arabische Emirate",
  "AF": "Afghanistan",
  "AG": "Antigua und Barbuda",
  "AI": "Anguilla",
  "AL": "Albanien",
  "AM": "Armenien",
  "AO": "Angola",
  "AQ": "Antarktis",
  "AR": "Argentinien",
  "AS": "Amerikanisch-Samoa",
  "AT": "Österreich",
  "AU": "Australien",
  "AW": "Aruba",
  "AX": "Åland",
  "AZ": "Aserbaidschan",
  "BA": "Bosnien und Herzegowina",
  "BB": "Barbados",
  "BD": "Bangladesch",
  "BE": "Belgien",
  "BF": "Burkina Faso",
  "BG": "Bulgarien",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint-Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei",
  "BO": "Bolivien",
  "BQ": "Bonaire",
  "BR": "Brasilien",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvetinsel",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Kanada",
  "CC": "Kokosinseln",
  "CD": "Demokratische Republik Kongo",
  "CF": "Zentralafrikanische Republik",
  "CG": "Kongo",
  "CH": "Schweiz",
  "CI": "Elfenbeinküste",
  "CK": "Cookinseln",
  "CL": "Chile",
  "CM": "Kamerun",
  "CN": "China",
  "CO": "Kolumbien",
  "CR": "Costa Rica",
  "CU": "Kuba",
  "CV": "Kap Verde",
  "CW": "Curaçao",
  "CX": "Weihnachtsinsel",
  "CY": "Zypern",
  "CZ": "Tschechien",
  "DE": "Deutschland",
  "DJ": "Dschibuti",
  "DK": "Dänemark",
  "DM": "Dominica",
  "DO": "Dominikanische Republik",
  "DZ": "Algerien",
  "EC": "Ecuador",
  "EE": "Estland",
  "EG": "Ägypten",
  "EH": "Westsahara",
  "ER": "Eritrea",
  "ES": "Spanien",
  "ET": "Äthiopien",
  "FI": "Finnland",
  "FJ": "Fidschi",
  "FK": "Falklandinseln",
  "FM": "Mikronesien",
  "FO": "Färöer",
  "FR": "Frankreich",
  "GA": "Gabun",
  "GB": "Vereinigtes Königreich",
  "GD": "Grenada",
  "GE": "Georgien",
  "GF": "Französisch-Guayana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Grönland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Äquatorialguinea",
  "GR": "Griechenland",
  "GS": "Südgeorgien",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hongkong",
  "HM": "Heard und McDonaldinseln",
  "HN": "Honduras",
  "HR": "Kroatien",
  "HT": "Haiti",
  "HU": "Ungarn",
  "ID": "Indonesien",
  "IE": "Irland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "Indien",
  "IO": "Britisches Territorium im Indischen Ozean",
  "IQ": "Irak",
  "IR": "Iran",
  "IS": "Island",
  "IT": "Italien",
  "JE": "Jersey",
  "JM": "Jamaika",
  "JO": "Jordanien",
  "JP": "Japan",
  "KE": "Kenia",
  "KG": "Kirgisistan",
  "KH": "Kambodscha",
  "KI": "Kiribati",
  "KM": "Komoren",
  "KN": "St. Kitts und Nevis",
  "KP": "Nordkorea",
  "KR": "Südkorea",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kasachstan",
  "LA": "Laos",
  "LB": "Libanon",
  "LC": "St. Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Litauen",
  "LU": "Luxemburg",
  "LV": "Lettland",
  "LY": "Libyen",
  "MA": "Marokko",
  "MC": "Monaco",
  "MD": "Moldau",
  "ME": "Montenegro",
  "MF": "Saint-Martin",
  "MG": "Madagaskar",
  "MH": "Marshallinseln",
  "MK": "Nordmazedonien",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolei",
  "MO": "Macau",
  "MP": "Nördliche Marianen",
  "MQ": "Martinique",
  "MR": "Mauretanien",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Malediven",
  "MW": "Malawi",
  "MX": "Mexiko",
  "MY": "Malaysia",
  "MZ": "Mosambik",
  "NA": "Namibia",
  "NC": "Neukaledonien",
  "NE": "Niger",
  "NF": "Norfolkinsel",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Niederlande",
  "NO": "Norwegen",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "Neuseeland",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "Französisch-Polynesien",
  "PG": "Papua-Neuguinea",
  "PH": "Philippinen",
  "PK": "Pakistan",
  "PL": "Polen",
  "PM": "Saint-Pierre und Miquelon",
  "PN": "Pitcairninseln",
  "PR": "Puerto Rico",
  "PS": "Palästina",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Katar",
  "RE": "Réunion",
  "RO": "Rumänien",
  "RS": "Serbien",
  "RU": "Russland",
  "RW": "Ruanda",
  "SA": "Saudi-Arabien",
  "SB": "Salomonen",
  "SC": "Seychellen",
  "SD": "Sudan",
  "SE": "Schweden",
  "SG": "Singapur",
  "SH": "St. Helena",
  "SI": "Slowenien",
  "SJ": "Spitzbergen und Jan Mayen",
  "SK": "Slowakei",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "Südsudan",
  "ST": "São Tomé und Príncipe",
  "SV": "El Salvador",
  "SX": "Sint Maarten",
  "SY": "Syrien",
  "SZ": "Swasiland",
  "TC": "Turks- und Caicosinseln",
  "TD": "Tschad",
  "TF": "Französische Süd- und Antarktisgebiete",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tadschikistan",
  "TK": "Tokelau",
  "TL": "Osttimor",
  "TM": "Turkmenistan",
  "TN": "Tunesien",
  "TO": "Tonga",
  "TR": "Türkei",
  "TT": "Trinidad und Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tansania",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "Amerikanische Überseeinseln",
  "US": "USA",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "VA": "Vatikanstadt",
  "VC": "St. Vincent und die Grenadinen",
  "VE": "Venezuela",
  "VG": "Britische Jungferninseln",
  "VI": "Amerikanische Jungferninseln",
  "VN": "Vietnam",
  "VU": "Vanuatu",
  "WF": "Wallis und Futuna",
  "WS": "Samoa",
  "YE": "Jemen",
  "YT": "Mayotte",
  "ZA": "Südafrika",
  "ZM": "Sambia",
  "ZW": "Simbabwe"
};

const POPULAR_DEST_CODES = ["BCN", "LIS", "IST", "FCO", "LHR", "CDG", "AMS", "DXB", "AYT", "CAI"];

// Ports apLocalizedCityName() — city name in the visitor's language,
// falling back through en/de.
function apLocalizedCityName(entry, lang) {
  const idx = { de: 2, en: 4, ar: 5, es: 7, fr: 8, it: 9, nl: 10 }[lang] || 2;
  return entry[idx] || entry[2];
}

function apByCode(code) {
  return AP.find((a) => a[0] === code) || null;
}

export { AP, COUNTRY_DE, POPULAR_DEST_CODES, apLocalizedCityName, apByCode };
