// Real copy extracted verbatim from the legacy app.js TRANSLATIONS dict —
// only this fixed key set (hero/search-card/service-tabs/trust/offer-card
// labels), not the whole parallel i18n system (see the migration plan:
// this app extends lib/translate.js instead of porting app.js TRANSLATIONS
// wholesale). Values must stay byte-identical to the source — do not
// paraphrase or "improve" the copy.
const LEGACY_STRINGS = {
  "de": {
    "hero_pill": "Echte Preise · Live-Verfügbarkeit",
    "hero_title1": "Günstige Flüge suchen",
    "hero_title2": "und weltweit",
    "hero_title_span": "vergleichen",
    "hero_sub": "Vergleiche hunderte Airlines, finde Verbindungen die sonst niemand findet — zum besten Preis.",
    "tab_flights": "Flüge",
    "tab_hotels": "Hotels",
    "tab_cars": "Mietwagen",
    "tab_insurance": "Versich.",
    "coming_soon_title": "Demnächst",
    "coming_soon_hotels": "Hotelbuchung kommt bald. Bleib dran!",
    "coming_soon_cars": "Mietwagen kommt bald. Bleib dran!",
    "coming_soon_insurance": "Reiseversicherung kommt bald. Bleib dran!",
    "trip_rr": "⇄ Hin- und Rückreise",
    "trip_ow": "→ Einfache Fahrt",
    "from_placeholder": "Von — Stadt oder Flughafen",
    "to_placeholder": "Nach — Stadt oder Flughafen",
    "depart_lbl": "Abflug",
    "return_lbl": "Rückkehr",
    "date_pick": "Datum wählen",
    "search_btn": "Suchen",
    "direct_chip": "✈ Direktflüge",
    "baggage_chip": "🏠 Mit Gepäck",
    "tax_note": "Alle Preise inkl. Steuern",
    "flex_hint": "💡 Tipp: Flexible Daten? Probiere ±3 Tage für günstigere Preise!",
    "det_direct": "Direktflug",
    "stops": "Stopps",
    "stop": "Stopp",
    "det_outbound": "Hinflug",
    "det_return": "Rückflug",
    "det_layover": "Aufenthalt in",
    "det_flight": "Flug",
    "det_title": "Flugdetails",
    "det_book_now": "Diesen Flug buchen",
    "perPerson": "pro Person",
    "fc_cabin": "Handgepäck",
    "fc_checked": "Aufgabegepäck",
    "bg_overview": "Gepäckübersicht",
    "bg_close": "Schließen"
  },
  "en": {
    "hero_pill": "Real prices · Live availability",
    "hero_title1": "Search cheap flights",
    "hero_title2": "and compare",
    "hero_title_span": "worldwide",
    "hero_sub": "Compare hundreds of airlines, find connections no one else can find — at the best price.",
    "tab_flights": "Flights",
    "tab_hotels": "Hotels",
    "tab_cars": "Car Rental",
    "tab_insurance": "Insure",
    "coming_soon_title": "Coming Soon",
    "coming_soon_hotels": "Hotel booking will be available soon. Stay tuned!",
    "coming_soon_cars": "Car rental will be available soon. Stay tuned!",
    "coming_soon_insurance": "Travel insurance will be available soon. Stay tuned!",
    "trip_rr": "⇄ Round trip",
    "trip_ow": "→ One way",
    "from_placeholder": "From — city or airport",
    "to_placeholder": "To — city or airport",
    "depart_lbl": "Depart",
    "return_lbl": "Return",
    "date_pick": "Select date",
    "search_btn": "Search",
    "direct_chip": "✈ Direct flights",
    "baggage_chip": "🏠 With baggage",
    "tax_note": "All prices incl. taxes",
    "flex_hint": "💡 Tip: Flexible dates? Try ±3 days for cheaper prices!",
    "det_direct": "Direct flight",
    "stops": "Stops",
    "stop": "Stop",
    "det_outbound": "Outbound",
    "det_return": "Return",
    "det_layover": "Layover in",
    "det_flight": "Flight",
    "det_title": "Flight details",
    "det_book_now": "Book this flight",
    "perPerson": "per person",
    "fc_cabin": "Cabin baggage",
    "fc_checked": "Checked baggage",
    "bg_overview": "Baggage overview",
    "bg_close": "Close"
  },
  "ar": {
    "hero_pill": "أسعار حقيقية · توفر فوري",
    "hero_title1": "ابحث وقارن الرحلات",
    "hero_title2": "الجوية بأفضل الأسعار",
    "hero_title_span": "حول العالم",
    "hero_sub": "قارن مئات شركات الطيران، واعثر على رحلات لا يجدها غيرك — بأفضل سعر.",
    "tab_flights": "طيران",
    "tab_hotels": "فنادق",
    "tab_cars": "سيارات",
    "tab_insurance": "تأمين",
    "coming_soon_title": "قريباً",
    "coming_soon_hotels": "حجز الفنادق سيكون متاحاً قريباً. ترقبونا!",
    "coming_soon_cars": "تأجير السيارات سيكون متاحاً قريباً. ترقبونا!",
    "coming_soon_insurance": "التأمين الصحي سيكون متاحاً قريباً. ترقبونا!",
    "trip_rr": "⇄ ذهاب وعودة",
    "trip_ow": "→ ذهاب فقط",
    "from_placeholder": "من — المدينة أو المطار",
    "to_placeholder": "إلى — المدينة أو المطار",
    "depart_lbl": "المغادرة",
    "return_lbl": "العودة",
    "date_pick": "اختر التاريخ",
    "search_btn": "بحث",
    "direct_chip": "✈ رحلات مباشرة",
    "baggage_chip": "🏠 مع أمتعة",
    "tax_note": "جميع الأسعار شاملة الضرائب",
    "flex_hint": "💡 نصيحة: تواريخ مرنة؟ جرّب ±3 أيام للحصول على أسعار أرخص!",
    "det_direct": "رحلة مباشرة",
    "stops": "توقفات",
    "stop": "توقف",
    "det_outbound": "الذهاب",
    "det_return": "العودة",
    "det_layover": "توقف في",
    "det_flight": "رحلة",
    "det_title": "تفاصيل الرحلة",
    "det_book_now": "احجز هذه الرحلة",
    "perPerson": "للشخص",
    "fc_cabin": "حقيبة يد",
    "fc_checked": "حقيبة مسجّلة",
    "bg_overview": "ملخص الحقائب",
    "bg_close": "إغلاق"
  },
  "es": {
    "hero_pill": "Precios reales · Disponibilidad en vivo",
    "hero_title1": "Busca vuelos baratos",
    "hero_title2": "en todo el mundo",
    "hero_title_span": "y compara",
    "hero_sub": "Compara cientos de aerolíneas, encuentra conexiones que nadie más encuentra — al mejor precio.",
    "tab_flights": "Vuelos",
    "tab_hotels": "Hoteles",
    "tab_cars": "Coches",
    "tab_insurance": "Seguro",
    "coming_soon_title": "Próximamente",
    "coming_soon_hotels": "La reserva de hoteles estará disponible pronto. ¡No te lo pierdas!",
    "coming_soon_cars": "El alquiler de coches estará disponible pronto. ¡No te lo pierdas!",
    "coming_soon_insurance": "El seguro de viaje estará disponible pronto. ¡No te lo pierdas!",
    "trip_rr": "⇄ Ida y vuelta",
    "trip_ow": "→ Solo ida",
    "from_placeholder": "Desde — ciudad o aeropuerto",
    "to_placeholder": "Hasta — ciudad o aeropuerto",
    "depart_lbl": "Salida",
    "return_lbl": "Regreso",
    "date_pick": "Seleccionar fecha",
    "search_btn": "Buscar",
    "direct_chip": "✈ Vuelos directos",
    "baggage_chip": "🏠 Con equipaje",
    "tax_note": "Todos los precios incl. impuestos",
    "flex_hint": "💡 Consejo: ¿Fechas flexibles? ¡Prueba ±3 días para precios más baratos!",
    "det_direct": "Vuelo directo",
    "stops": "Escalas",
    "stop": "Escala",
    "det_outbound": "Ida",
    "det_return": "Vuelta",
    "det_layover": "Escala en",
    "det_flight": "Vuelo",
    "det_title": "Detalles del vuelo",
    "det_book_now": "Reservar este vuelo",
    "perPerson": "por persona",
    "fc_cabin": "Equipaje de mano",
    "fc_checked": "Equipaje facturado",
    "bg_overview": "Resumen del equipaje",
    "bg_close": "Cerrar"
  },
  "fr": {
    "hero_pill": "Prix réels · Disponibilité en temps réel",
    "hero_title1": "Recherchez des vols pas chers",
    "hero_title2": "dans le monde entier",
    "hero_title_span": "et comparez",
    "hero_sub": "Comparez des centaines de compagnies aériennes, trouvez des correspondances que personne d'autre ne trouve — au meilleur prix.",
    "tab_flights": "Vols",
    "tab_hotels": "Hôtels",
    "tab_cars": "Location de voitures",
    "tab_insurance": "Assurance",
    "coming_soon_title": "Bientôt disponible",
    "coming_soon_hotels": "La réservation d'hôtels sera bientôt disponible. Restez à l'écoute !",
    "coming_soon_cars": "La location de voitures sera bientôt disponible. Restez à l'écoute !",
    "coming_soon_insurance": "L'assurance voyage sera bientôt disponible. Restez à l'écoute !",
    "trip_rr": "⇄ Aller-retour",
    "trip_ow": "→ Aller simple",
    "from_placeholder": "De — ville ou aéroport",
    "to_placeholder": "À — ville ou aéroport",
    "depart_lbl": "Départ",
    "return_lbl": "Retour",
    "date_pick": "Choisir une date",
    "search_btn": "Rechercher",
    "direct_chip": "✈ Vols directs",
    "baggage_chip": "🏠 Avec bagages",
    "tax_note": "Tous les prix taxes incluses",
    "flex_hint": "💡 Astuce : dates flexibles ? Essayez ±3 jours pour des prix plus intéressants !",
    "det_direct": "Vol direct",
    "stops": "Escales",
    "stop": "Escale",
    "det_outbound": "Aller",
    "det_return": "Retour",
    "det_layover": "Escale à",
    "det_flight": "Vol",
    "det_title": "Détails du vol",
    "det_book_now": "Réserver ce vol",
    "perPerson": "par personne",
    "fc_cabin": "Bagage cabine",
    "fc_checked": "Bagage en soute",
    "bg_overview": "Récapitulatif des bagages",
    "bg_close": "Fermer"
  },
  "it": {
    "hero_pill": "Prezzi reali · Disponibilità in tempo reale",
    "hero_title1": "Cerca voli economici",
    "hero_title2": "in tutto il mondo",
    "hero_title_span": "e confronta",
    "hero_sub": "Confronta centinaia di compagnie aeree, trova collegamenti che nessun altro trova — al miglior prezzo.",
    "tab_flights": "Voli",
    "tab_hotels": "Hotel",
    "tab_cars": "Noleggio auto",
    "tab_insurance": "Assicurazione",
    "coming_soon_title": "Prossimamente",
    "coming_soon_hotels": "La prenotazione hotel sarà presto disponibile. Resta sintonizzato!",
    "coming_soon_cars": "Il noleggio auto sarà presto disponibile. Resta sintonizzato!",
    "coming_soon_insurance": "L'assicurazione di viaggio sarà presto disponibile. Resta sintonizzato!",
    "trip_rr": "⇄ Andata e ritorno",
    "trip_ow": "→ Solo andata",
    "from_placeholder": "Da — città o aeroporto",
    "to_placeholder": "A — città o aeroporto",
    "depart_lbl": "Partenza",
    "return_lbl": "Ritorno",
    "date_pick": "Seleziona data",
    "search_btn": "Cerca",
    "direct_chip": "✈ Voli diretti",
    "baggage_chip": "🏠 Con bagaglio",
    "tax_note": "Tutti i prezzi tasse incluse",
    "flex_hint": "💡 Consiglio: date flessibili? Prova ±3 giorni per prezzi più convenienti!",
    "det_direct": "Volo diretto",
    "stops": "Scali",
    "stop": "Scalo",
    "det_outbound": "Andata",
    "det_return": "Ritorno",
    "det_layover": "Scalo a",
    "det_flight": "Volo",
    "det_title": "Dettagli del volo",
    "det_book_now": "Prenota questo volo",
    "perPerson": "a persona",
    "fc_cabin": "Bagaglio a mano",
    "fc_checked": "Bagaglio da stiva",
    "bg_overview": "Riepilogo bagagli",
    "bg_close": "Chiudi"
  },
  "nl": {
    "hero_pill": "Echte prijzen · Realtime beschikbaarheid",
    "hero_title1": "Zoek goedkope vluchten",
    "hero_title2": "wereldwijd",
    "hero_title_span": "en vergelijk",
    "hero_sub": "Vergelijk honderden maatschappijen, vind verbindingen die niemand anders vindt — voor de beste prijs.",
    "tab_flights": "Vluchten",
    "tab_hotels": "Hotels",
    "tab_cars": "Autoverhuur",
    "tab_insurance": "Verzekering",
    "coming_soon_title": "Binnenkort beschikbaar",
    "coming_soon_hotels": "Hotelboekingen zijn binnenkort beschikbaar. Blijf op de hoogte!",
    "coming_soon_cars": "Autoverhuur is binnenkort beschikbaar. Blijf op de hoogte!",
    "coming_soon_insurance": "Reisverzekering is binnenkort beschikbaar. Blijf op de hoogte!",
    "trip_rr": "⇄ Retour",
    "trip_ow": "→ Enkele reis",
    "from_placeholder": "Van — stad of luchthaven",
    "to_placeholder": "Naar — stad of luchthaven",
    "depart_lbl": "Vertrek",
    "return_lbl": "Terugreis",
    "date_pick": "Datum kiezen",
    "search_btn": "Zoeken",
    "direct_chip": "✈ Directe vluchten",
    "baggage_chip": "🏠 Met bagage",
    "tax_note": "Alle prijzen incl. belastingen",
    "flex_hint": "💡 Tip: flexibele data? Probeer ±3 dagen voor goedkopere prijzen!",
    "det_direct": "Directe vlucht",
    "stops": "Tussenstops",
    "stop": "Tussenstop",
    "det_outbound": "Heenreis",
    "det_return": "Terugreis",
    "det_layover": "Tussenstop in",
    "det_flight": "Vlucht",
    "det_title": "Vluchtdetails",
    "det_book_now": "Boek deze vlucht",
    "perPerson": "per persoon",
    "fc_cabin": "Handbagage",
    "fc_checked": "Ruimbagage",
    "bg_overview": "Bagageoverzicht",
    "bg_close": "Sluiten"
  }
};

export { LEGACY_STRINGS };
